### ISSUE TITLE
登录不了，提示密码错误

### ISSUE THREAD

**Issue by easymoneysniperrr** [aehyok/vue-qiankun#14]
<img width="1477" alt="image" src="https://user-images.githubusercontent.com/45280905/229062118-d52f6b22-f552-44ef-908a-c9a1c73af95f.png">
大佬请教下这是哪里的问题

**Comment by aehyok** [comment]
我这里调用了 接口 18888888888   123456试试

**Comment by aehyok** [comment]
或者你把这个接口注释一下
