### ISSUE TITLE
webpack-app 项目启动报错，"../../common/qiankun/public-path.js"模块未找到

### ISSUE THREAD

**Issue by liumemgmei** [aehyok/vue-qiankun#2]
目前项目用的是 dev分支，不知道楼主是不是特意不配置这个文件，由开发者自己配置

**Comment by aehyok** [comment]
@liumemgmei 我设置的忽略文件夹为qiankun导致的，你可以重新clone 运行，我已经将代码提交上去了

**Comment by liumemgmei** [comment]
嗯，谢谢。react-app 项目启动的时候报错，帮忙看下
![image](https://user-images.githubusercontent.com/33617202/125739561-47646813-2afd-4361-9783-e783f2d8bdfd.png)

**Comment by aehyok** [comment]
react-app 我刚创建 还没开始搞进去，目前主要在搞map-app和webpack-app,过段时间准备搞react-app

**Comment by liumemgmei** [comment]
好的，那我目前先看下map-app和webpack-app，感谢分享~

**Comment by aehyok** [comment]
@liumemgmei 有问题及时留言，我看到就会反馈的。
