### ISSUE TITLE
大佬，项目启动以后有两处控制台报错

### ISSUE THREAD

**Issue by wanliyunyan** [aehyok/vue-qiankun#3]
Home页面控制台，有时候就有，有时候就没有
![image](https://user-images.githubusercontent.com/10751248/162566894-e4ade468-48b9-4069-8c78-64e00951faa2.png)

进入子项目以后
![image](https://user-images.githubusercontent.com/10751248/162567068-e3a345de-c1fb-4ba3-946e-c0157ea0dd2c.png)
![image](https://user-images.githubusercontent.com/10751248/162567076-043df5f9-607c-423c-b29e-f0686021645f.png)

这些错误，不影响开发与打包，这是什么问题呢？

**Comment by aehyok** [comment]
map-app 和webpack-app 两个字应用要启动一下，你启动了吗？

**Comment by wanliyunyan** [comment]
@aehyok 给大佬添麻烦了，是因为没有启动子项目

**Comment by aehyok** [comment]
@wanliyunyan 解决了就好
