### ISSUE TITLE
大佬，小白问几个问题

### ISSUE THREAD

**Issue by wanliyunyan** [aehyok/vue-qiankun#4]
最近公司要做微前端，发现您这个项目是目前GitHub上能找到的最完美的项目，但是还有几个问题，没想明白

1. 根目录下面的` common/component` 里面中所有的el的组件，我看你就是直接引用的，但是我公司是用的antd的组件，我也是直接引用，

```
<script setup lang="ts">

</script>

<template>
  <a-button type="primary">Primary</a-button>
</template>

<style scoped>

</style>
```
`[plugin:vite:import-analysis] Failed to resolve import "ant-design-vue/es/button/style/css" from "..\common\components\test.vue". Does the file exist?`
但是antd提示我没有css，确实是没有css，但是您使用的el组件就没有提示，这是为什么呢？

2. 我看还有 `import { format } from 'date-fns' `这样直接引用的组件，但是common和webpack-app-ts 根本不在一个根目录也不报错，可以这样写吗？
3.  `"common": "file:../../common"`好像删了也不影响什么.........

希望大佬指点迷津

**Comment by aehyok** [comment]
3: 这个是我在尝试 想把这个路径缩短一些，但是这种方式可能不行，或者我的写法还有问题

**Comment by aehyok** [comment]
2：写肯定是能用的，因为文件是通过路径去import的，就是在vscode中 可能会有提示

**Comment by aehyok** [comment]
1：我这相当于全局引入的，所以组件在开发时肯定不会出错的，看你报错好像是局部引入吗？

**Comment by wanliyunyan** [comment]
哎呀，我明白我的错误了，关于第三个问题，我在网上找个方案   https://github.com/gaiyonghuyichengxian/lerna-vue3-component    ，就是相当于把你的common写成一个完整的项目，感觉这么写能更优雅点，你有可以看看。

**Comment by aehyok** [comment]
@wanliyunyan   牛逼 多谢大佬，学到了

**Comment by Yang-KaiXin** [comment]
http://vue.tuokecat.com 上的demo
问题：在webpack-app 微应用（5、动态表单设计器）菜单下，拖拽一个文本框然后删除，在进行文本框拖拽就会出现两个。

**Comment by aehyok** [comment]
> http://vue.tuokecat.com 上的demo 问题：在webpack-app 微应用（5、动态表单设计器）菜单下，拖拽一个文本框然后删除，在进行文本框拖拽就会出现两个。

这个还待继续优化，哈哈

**Comment by wanliyunyan** [comment]
@aehyok 生产环境第一次加载子项目，网速不好的时候，需要下载10秒，有没有什么好的loading方案？？？

**Comment by aehyok** [comment]
> @aehyok 生产环境第一次加载子项目，网速不好的时候，需要下载10秒，有没有什么好的loading方案？？？

这么久？？文件很大吗？还是网络实在太差？

**Comment by wanliyunyan** [comment]
@aehyok 我看最大的文件才1M多，一共下载4M多，在网速差的情况下，有啥方案吗？这时候已经不走onload事件了
