### ISSUE TITLE
你好，请教个问题，pnpm 不同 vue 版本引用会报版本错误

### ISSUE THREAD

**Issue by zhl1232** [aehyok/vue-qiankun#5]
你好，请教一下，你有没有遇到过，子应用分别是 vue2 和 vue3，这时用 pnpm 安装，启动时会报这个。

![image](https://user-images.githubusercontent.com/30594030/168727446-6b8711e2-ed90-4f7f-8152-77838d6b2397.png)

**Comment by aehyok** [comment]
vue2和vue3都不是在根安装的吧？

**Comment by zhl1232** [comment]
> vue2和vue3都不是在根安装的吧？

之前是根目录安装的 vue3 ，子应用安装的 vue2。然后换到 vue2 和 3 都在子应用安装。好像都不行。

**Comment by aehyok** [comment]
@zhl1232 子应用package.json什么样，可以截图看看嘛

**Comment by zhl1232** [comment]
![image](https://user-images.githubusercontent.com/30594030/168941840-d51d7067-4420-4543-995e-e72f76c88d77.png)

vue2 子应用是这样的，然后如果使用 npm 的 nomorepo 是没问题的。。
