### ISSUE TITLE
你好，问一个问题

### ISSUE THREAD

**Issue by StephenWu5** [aehyok/vue-qiankun#6]
大佬这个提示是什么问题啊

运行pnpm i 时发现的

![image](https://user-images.githubusercontent.com/32475322/169692896-247b44a0-9860-4bf5-9f33-6095a481203b.png)

pnpm 版本 7.1.3
nodejs 16.15
系统：ubuntu20.04

**Comment by StephenWu5** [comment]
I'm not sure if this is a pnpm v7 thing or something in the vite workspace causing that error. I had to remove the packages/playground directory just to get pnpm i to complete on my machine, then manually diffed the pnpm-lock.yaml to grab only what was needed to swap out esbuild ^0.14.27 for 0.14.34

**Comment by StephenWu5** [comment]
大佬有个后续问题： pnpm i 可以执行，然后目录下没有出现 node_modules ，无法运行起来？
![image](https://user-images.githubusercontent.com/32475322/169694047-3f1c9d11-5052-416c-983f-b5323e143ffd.png)

**Comment by aehyok** [comment]
> 大佬有个后续问题： pnpm i 可以执行，然后目录下没有出现 node_modules ，无法运行起来？

要单独要主应用和子应用目录下执行

**Comment by StephenWu5** [comment]
【要单独要主应用和子应用目录下执行】不是原因，是需要在根目录下新建一个空的common文件夹。

可以跑起来了。🐒🐒🐒

![image](https://user-images.githubusercontent.com/32475322/169835211-d88687da-c5eb-4eb7-ae16-c522e7ac1190.png)
