### ISSUE TITLE
运行当前项目使用什么命令？ npm run

### ISSUE THREAD

**Issue by savelifeme** [aehyok/vue-qiankun#7]
将代码拉取到本地，找不到运行当前项目的命令

![image](https://user-images.githubusercontent.com/32872731/186352069-aec73680-4fdf-4a52-8bb3-e0e2afcf8937.png)

**Comment by aehyok** [comment]
![image](https://user-images.githubusercontent.com/5900140/186378800-2634d2cb-6cbe-4e57-9ebf-48fb48ae81bb.png)
我README里写了 你试试看

**Comment by savelifeme** [comment]
> ![image](https://user-images.githubusercontent.com/5900140/186378800-2634d2cb-6cbe-4e57-9ebf-48fb48ae81bb.png) 我README里写了 你试试看

抱歉，这么晚还打扰你了

第一次接触乾坤与vue相结合的框架，没有找到运行命令

不知道咋切换vue2，不知道怎么入手![26EE2B6A](https://user-images.githubusercontent.com/32872731/186437224-4b3cbd60-831a-4aa2-9a9f-f63b1540f9fc.png)

![image](https://user-images.githubusercontent.com/32872731/186439513-fef6790a-6b2f-492b-8fbc-a4b3c0b5eb9b.png)

链接打不开了
![image](https://user-images.githubusercontent.com/32872731/186439704-151d71d4-b9e9-4830-8688-c56f49bfeae4.png)

我已使用pnpm i 安装好了，

我尝试了，package.json 里面的命令， 报错了，可能不是这么运行的，
![image](https://user-images.githubusercontent.com/32872731/186440132-808673d7-56e5-4621-99a7-820004c7ca0d.png)

我是使用 window 开发的 使用管理员执行 报错了，我找不到也想不到运行方法了， 
![image](https://user-images.githubusercontent.com/32872731/186440232-24efcf72-e824-4324-88f9-e6c7c4016a1d.png)


这个运行命令希望你在闲暇之余，讲解一下，[开心]

**Comment by aehyok** [comment]
https://github.com/aehyok/vue-qiankun/blob/dev/docs/qiankun.md  试一下这个看看，简单一点
